### ISSUE TITLE
Scale Profile images correctly

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8-services/fabric8-notification#31]
When user has an imageURL from gravatar we can easily append "?s=22" to the URL and we're good, but some have imageURL from github which contain another URL parameter "?v=n" appending "?s=22" to that has no effect.

The image size function need to take the additional parameter into account

**Comment by aslakknutsen** [comment]
@mindreeper2420 We probably want to add CSS as a safe guard here as well?

**Comment by mindreeper2420** [comment]
@aslakknutsen sure thing. I’ll add it to each spot with a profile image.
