### ISSUE TITLE
Use service account token issued by Auth to get user's email from Auth service

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-notification#52]
As an offshoot of https://github.com/fabric8-services/fabric8-auth/pull/237#issuecomment-354867619

1. When notification service comes up, call Auth service API to request for service account token, and keep it in memory.

2. Subsequently use the token from configuration memory object.

3. On the auth side, check for service account token, and based on that show the email .

**Comment by sbose78** [comment]
CC: @alexeykazakov

**Comment by alexeykazakov** [comment]
This is needed to be done to support email notifications for users with private emails.

**Comment by aslakknutsen** [comment]
@alexeykazakov This is similar to the new f8tenant 'login', correct?

**Comment by alexeykazakov** [comment]
@aslakknutsen correct.
